# Generated by Django 2.1.7 on 2019-03-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190327_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='media/no-img.jpg', upload_to='media/'),
        ),
    ]
